#!/bin/bash

CONFIG_FILES="$HOME/.config/waybar/config.jsonc $HOME/.config/waybar/style.css"

killall waybar
while pgrep -u $UID -x waybar >/dev/null; do sleep 1; done

while true; do
    waybar &
    inotifywait -e create,modify $CONFIG_FILES
    killall -SIGUSR2 waybar
done
# trap "killall waybar" EXIT

# while true; do
#     logger -i "$0: Starting waybar in the background..."
#     waybar &
#     logger -i "$0: Started waybar PID=$!. Waiting for modifications to ${CONFIG_FILES}..."
#     inotifywait -e modify ${CONFIG_FILES} 2>&1 | logger -i
#     logger -i "$0: inotifywait returned $?. Killing all waybar processes..."
#     killall waybar 2>&1 | logger -i
#     logger -i "$0: killall waybar returned $?, wait a sec..."
#     sleep 1
# done