;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================


include-directory = /home/oriely/.config/polybar/includes

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini


[colors]
background = ${xrdb:color0}
foreground = ${xrdb:color6}
foreground-alt=${xrdb:color0}
i3_background = ${xrdb:color5}
i3_foreground = ${xrdb:color7}
i3_urgent_background = ${xrdb:color5}
i3_unfocused_foreground = ${xrdb:color2}

status_good = ${xrdb:color7}
status_sub = ${xrdb:color6}
status_bad = ${xrdb:color5}

text-color = ${xrdb:color7}
line-color = ${xrdb:color7}
transparent = #00FFFFFF

[pycol]
0 = ${xrdb:color0}
1 = ${xrdb:color1}
2 = ${xrdb:color2}
3 = ${xrdb:color3}
4 = ${xrdb:color4}
5 = ${xrdb:color5}
6 = ${xrdb:color6}
7 = ${xrdb:color7}
8 = ${xrdb:color8}
9 = ${xrdb:color9}

[const]
font-0 = Iosevka:style=Regular:size=12;5
font-1 = FontAwesome6Free:style=Solid:size=15;5
font-2 = FontAwesome6Free:style=Regular:size=15;5
font-3 = FontAwesome6Brands:style=Regular:size=15;5
font-4 = IosevkaNerdFont:style=Regular:size=18;0


[section/base]
modules-left = i3 xwindow

module-margin-left = 0
module-margin-right = 0

border-left-size = 15pt
border-right-size = 15pt
border-top-size = 15pt
border-bottom-size = 0
border-color = #00000000
line-size = 2pt
padding-left = 0
padding-right = 0
font-0 = ${const.font-0}
font-1 = ${const.font-1}
font-2 = ${const.font-2}
font-3 = ${const.font-3}
font-4 = ${const.font-4}
background = #aa2F343F
tray-position = center
width = 100%
height = 25pt
[bar/main]
monitor = ${env:MONITOR:eDP1}
inherit = section/base

radius = 0
separator-foreground = ${colors.disabled}
modules-center = mpd
modules-right = memory cpu date pulseaudio
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true


[bar/secondary]
monitor = ${env:MONITOR:eDP1}
inherit = section/base
width = 100%
radius = 0
separator-foreground = ${colors.disabled}
modules-right =  memory cpu date pulseaudio
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true
